In [14]:
import numpy as np

In [15]:
data=np.genfromtxt(r"C:\Users\DELL\Downloads\train_extended.csv",skip_header=1,delimiter=',')

In [16]:
data

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [17]:
#what is max and min of length

In [18]:
length=data[:,0:1]
length

array([[1.575 ],
       [1.2375],
       [1.45  ],
       ...,
       [1.125 ],
       [1.625 ],
       [1.5875]])

In [19]:
x=np.max(length)
print('max of len',x)
x1=np.min(length)
print('min of len',x1)

max of len 7.58349125
min of len 0.0


In [20]:
#find the difference between max and min of length 

In [21]:
value=np.max(data)-np.min(data)
print('difference between max and min of length: ',value)

difference between max and min of length:  80.10151225


In [22]:
#find columnwise avaerage

In [23]:
length=data[:,0:1]
length

array([[1.575 ],
       [1.2375],
       [1.45  ],
       ...,
       [1.125 ],
       [1.625 ],
       [1.5875]])

In [24]:
value=np.sum(length)
value

262489.61599125003

In [25]:
print('average of length: ',value/len(data))

average of length:  1.3124480799562501


In [26]:
diameter=data[:,1:2]
diameter

array([[1.225 ],
       [1.    ],
       [1.1625],
       ...,
       [0.9125],
       [1.275 ],
       [1.25  ]])

In [27]:
value=np.sum(diameter)
value
print('average of diameter: ',value/len(data))

average of diameter:  1.020320357165


In [28]:
height=data[:,2:3]
height

array([[0.375 ],
       [0.375 ],
       [0.4125],
       ...,
       [0.2875],
       [0.4125],
       [0.3875]])

In [29]:
value=np.sum(height)
value
print('average of height: ',value/len(data))

average of height:  0.34602787104999994


In [30]:
weight=data[:,3:4]
weight

array([[31.22697425],
       [21.885814  ],
       [28.25027675],
       ...,
       [10.886208  ],
       [33.89182725],
       [34.37376875]])

In [31]:
value=np.sum(weight)
value
print('average of weight: ',value/len(data))

average of weight:  23.123436312982403


In [32]:
shucked_weight=data[:,4:5]
shucked_weight

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [33]:
value=np.sum(shucked_weight)
value
print('average of shucked weight: ',value/len(data))

average of shucked weight:  9.989370248049001


In [34]:
viscera_weight=data[:,5:6]
viscera_weight

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [35]:
value=np.sum(viscera_weight)
value
print('average of viscera weight: ',value/len(data))

average of viscera weight:  4.993180956748749


In [36]:
shell_weight=data[:,6:7]
shell_weight

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [37]:
value=np.sum(shell_weight)
value
print('average of shell weight: ',value/len(data))

average of shell weight:  6.634229147607001


In [38]:
age=data[:,7:8]
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [39]:
value=np.sum(age)
value
print('average of age: ',value/len(data))

average of age:  9.950615


In [40]:
#find out all the age whose height is >0.4

In [54]:
height=data[:,2:3]
h=height>0.4

In [55]:
data[:,-1][h]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
#what is the average weight and height of the persons who's age is 10

In [63]:
value=np.sum(weight)+np.sum(height)
average=value/2
average

2346946.4184032404

In [43]:
shell_weight=data[:,6:7]
shell_weight

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [44]:
value=np.sum(shell_weight)
print('total of shell weight:',value)

total of shell weight: 1326845.8295214002


In [45]:
#how many persons belongs to each & every unique age

In [46]:
unique_age=data[:,7:8]
unique_age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [47]:
unique_age,counts_of_age=np.unique(data,return_counts=True)
print(unique_age)
print(counts_of_age)
print('no.of persons belong to age 1: ',counts_of_age[0])
print('no.of persons belong to age 2: ',counts_of_age[1])
print('no.of persons belong to age 3: ',counts_of_age[2])
print('no.of persons belong to age 4: ',counts_of_age[3])
print('no.of persons belong to age 5: ',counts_of_age[4])
print('no.of persons belong to age 6: ',counts_of_age[5])
print('no.of persons belong to age 7: ',counts_of_age[6])
print('no.of persons belong to age 8: ',counts_of_age[7])
print('no.of persons belong to age 9: ',counts_of_age[8])
print('no.of persons belong to age 10: ',counts_of_age[9])
print('no.of persons belong to age 11: ',counts_of_age[10])
print('no.of persons belong to age 12: ',counts_of_age[11])
print('no.of persons belong to age 13: ',counts_of_age[12])
print('no.of persons belong to age 14: ',counts_of_age[13])
print('no.of persons belong to age 15: ',counts_of_age[14])
print('no.of persons belong to age 16: ',counts_of_age[15])
print('no.of persons belong to age 17: ',counts_of_age[16])
print('no.of persons belong to age 18: ',counts_of_age[17])
print('no.of persons belong to age 19: ',counts_of_age[18])
print('no.of persons belong to age 20: ',counts_of_age[19])
print('no.of persons belong to age 21: ',counts_of_age[20])
print('no.of persons belong to age 22: ',counts_of_age[21])
print('no.of persons belong to age 23: ',counts_of_age[22])
print('no.of persons belong to age 24: ',counts_of_age[23])
print('no.of persons belong to age 25: ',counts_of_age[24])
print('no.of persons belong to age 26: ',counts_of_age[25])
print('no.of persons belong to age 27: ',counts_of_age[26])
print('no.of persons belong to age 29: ',counts_of_age[27])

[0.00000000e+00 1.25000000e-02 1.41747500e-02 ... 7.86964952e+01
 7.87974353e+01 8.01015122e+01]
[147   4   5 ...   1   3   7]
no.of persons belong to age 1:  147
no.of persons belong to age 2:  4
no.of persons belong to age 3:  5
no.of persons belong to age 4:  27
no.of persons belong to age 5:  5
no.of persons belong to age 6:  30
no.of persons belong to age 7:  6
no.of persons belong to age 8:  42
no.of persons belong to age 9:  8
no.of persons belong to age 10:  240
no.of persons belong to age 11:  23
no.of persons belong to age 12:  185
no.of persons belong to age 13:  3
no.of persons belong to age 14:  1
no.of persons belong to age 15:  4
no.of persons belong to age 16:  1
no.of persons belong to age 17:  1
no.of persons belong to age 18:  2
no.of persons belong to age 19:  120
no.of persons belong to age 20:  357
no.of persons belong to age 21:  247
no.of persons belong to age 22:  924
no.of persons belong to age 23:  807
no.of persons belong to age 24:  49
no.of persons belong 

In [48]:
#what is the difference between shucked weight and viscuse weight

In [49]:
data1=data[:,4:5]
data1

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [50]:
data2=data[:,5:6]
data2

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [51]:
value=np.sum(data1)-np.sum(data2)
print('difference between shucked weight and viscuse weight: ',value)

difference between shucked weight and viscuse weight:  999237.8582600503


In [38]:
#what is the average weight if we include shucked weight,viscera weight and shell weight

In [70]:
data3=data[:,6:7]
data3

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [71]:
value=np.sum(data1)+np.sum(data2)+np.sum(data3)
print('average weight if we include shucked weight and viscera weight and shell weight: ',value/3)

average weight if we include shucked weight and viscera weight and shell weight:  1441118.6901603166
