In [1]:
import numpy as np

In [3]:
data=np.genfromtxt(r"C:\Users\DELL\Downloads\tipsf.csv",skip_header=1,delimiter=',')

In [4]:
data

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [10]:
#what is the total bill value

In [53]:
total_bill=data[:,1:2]
total_bill

array([[16.99],
       [10.34],
       [21.01],
       [23.68],
       [24.59],
       [25.29],
       [ 8.77],
       [26.88],
       [15.04],
       [14.78],
       [10.27],
       [35.26],
       [15.42],
       [18.43],
       [14.83],
       [21.58],
       [10.33],
       [16.29],
       [16.97],
       [20.65],
       [17.92],
       [20.29],
       [15.77],
       [39.42],
       [19.82],
       [17.81],
       [13.37],
       [12.69],
       [21.7 ],
       [19.65],
       [ 9.55],
       [18.35],
       [15.06],
       [20.69],
       [17.78],
       [24.06],
       [16.31],
       [16.93],
       [18.69],
       [31.27],
       [16.04],
       [17.46],
       [13.94],
       [ 9.68],
       [30.4 ],
       [18.29],
       [22.23],
       [32.4 ],
       [28.55],
       [18.04],
       [12.54],
       [10.29],
       [34.81],
       [ 9.94],
       [25.56],
       [19.49],
       [38.01],
       [26.41],
       [11.24],
       [48.27],
       [20.29],
       [13.81],
       [

In [54]:
np.sum(total_bill)

4827.77

In [24]:
#what is total tip value

In [56]:
total_tip=data[:,2:3]
total_tip

array([[ 1.01],
       [ 1.66],
       [ 3.5 ],
       [ 3.31],
       [ 3.61],
       [ 4.71],
       [ 2.  ],
       [ 3.12],
       [ 1.96],
       [ 3.23],
       [ 1.71],
       [ 5.  ],
       [ 1.57],
       [ 3.  ],
       [ 3.02],
       [ 3.92],
       [ 1.67],
       [ 3.71],
       [ 3.5 ],
       [ 3.35],
       [ 4.08],
       [ 2.75],
       [ 2.23],
       [ 7.58],
       [ 3.18],
       [ 2.34],
       [ 2.  ],
       [ 2.  ],
       [ 4.3 ],
       [ 3.  ],
       [ 1.45],
       [ 2.5 ],
       [ 3.  ],
       [ 2.45],
       [ 3.27],
       [ 3.6 ],
       [ 2.  ],
       [ 3.07],
       [ 2.31],
       [ 5.  ],
       [ 2.24],
       [ 2.54],
       [ 3.06],
       [ 1.32],
       [ 5.6 ],
       [ 3.  ],
       [ 5.  ],
       [ 6.  ],
       [ 2.05],
       [ 3.  ],
       [ 2.5 ],
       [ 2.6 ],
       [ 5.2 ],
       [ 1.56],
       [ 4.34],
       [ 3.51],
       [ 3.  ],
       [ 1.5 ],
       [ 1.76],
       [ 6.73],
       [ 3.21],
       [ 2.  ],
       [

In [57]:
np.sum(total_tip)

731.5799999999999

In [ ]:
#count how many sundays,saturday,thrusday,fridays are there

In [6]:
unique,counts=np.unique(data[:,5],return_counts=True)
print(unique)
print(counts)

[0. 1. 2. 3.]
[87 76 62 19]


In [9]:
sun=counts[0]
sat=counts[1]
thrus=counts[2]
fri=counts[3]
print('sudays are: ',sun)
print('saturdays are: ',sat)
print('thrusdays are: ',thrus)
print('friday are: ',fri)

sudays are:  87
saturdays are:  76
thrusdays are:  62
friday are:  19


In [ ]:
#how many smokers are there

In [67]:
count=np.count_nonzero(data[:,4])
print('somkers are',count)

somkers are 93


In [68]:
#what is average tip is given by male and female

In [61]:
y=(data[:,1:2])
z=(data[:,3:4])

In [84]:
unique,counts=np.unique(data[:,4],return_counts=True)
print(unique)
print(counts)

[0. 1.]
[151  93]


In [47]:
male=counts[0]
print('males are:',male)
female=counts[1]
print('females are:',female)

males are: 151
females are: 93


In [14]:
#how much amount spent by female and male

In [78]:
#what is the min and max tip given

In [79]:
x=np.max(total_tip)
print('maximum tip is:',x)
x1=np.min(total_tip)
print('minimum tip is:',x1)

maximum tip is: 10.0
minimum tip is: 1.0


In [20]:
#how many male and female are going for dinner and lunch

In [72]:
unique,counts=np.unique(data[:,6],return_counts=True)
print(unique)
print(counts)

[0. 1.]
[176  68]


In [73]:
dinner=counts[0]
print('dinner:',dinner)
lunch=counts[1]
print('lunch :',lunch)

dinner: 176
lunch : 68


In [77]:
male[:1]

IndexError: invalid index to scalar variable.

In [21]:
#find out average size

In [28]:
size=data[:,7:]
size

array([[2.],
       [3.],
       [3.],
       [2.],
       [4.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [3.],
       [3.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],

In [31]:
x=np.sum(size)
x

627.0

In [33]:
print('average of size',x/len(size))

average of size 2.569672131147541


In [34]:
#how many female smokers and male smokers are there

In [36]:
unique,counts=np.unique(data[:,4],return_counts=True)
print(unique)
print(counts)

[0. 1.]
[151  93]


In [40]:
male=counts[0]
print('male somkers:',male)
female=counts[1]
print('female somkers:',female)

male somkers: 151
female somkers: 93
